---
- name: Security task
  include_tasks: security.yml

- name: Add repositories (RedHat)
  include_tasks: repos_redhat.yml
  when: ansible_facts['os_family'] == "RedHat"

- name: Add repositories (Debian)
  include_tasks: repos_debian.yml
  when: ansible_facts['os_family'] == "Debian"

- name: Install EPEL release and development tools on Rocky/CentOS
  when: ansible_os_family == "RedHat"
  block:
    - name: Install epel-release
      yum:
        name: epel-release
        state: present

    - name: Install development tools
      yum:
        name:
          - "@Development Tools"
          - python3
          - python3-devel
          - python3-pip
          - git
          - wget
          - curl
        state: present

- name: Install development tools on Ubuntu
  when: ansible_os_family == "Debian"
  block:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install development tools
      apt:
        name:
          - build-essential
          - python3
          - python3-dev
          - python3-pip
          - git
          - wget
          - curl
        state: present
