---
- name: Security task
  include_tasks: security.yml

- name: Add repositories (RedHat)
  include_tasks: repos_redhat.yml
  when: ansible_facts['os_family'] == "RedHat"

- name: Add repositories (Debian)
  include_tasks: repos_debian.yml
  when: ansible_facts['os_family'] == "Debian"