---
- name: Security task
  include_tasks: security.yml

- name: Add repositories (RedHat)
  include_tasks: repos_redhat.yml
  when: ansible_facts['os_family'] == "RedHat"

- name: Add repositories (Debian)
  include_tasks: repos_debian.yml
  when: ansible_facts['os_family'] == "Debian"

- name: Install EPEL release and development tools on Rocky/CentOS
  when: ansible_os_family == "RedHat"
  block:
    - name: Install epel-release
      yum:
        name: epel-release
        state: present

    - name: Install development tools
      yum:
        name:
          - "@Development Tools"
          - python3
          - python3-devel
          - python3-pip
          - git
          - wget
          - curl
        state: present

- name: Install development tools on Ubuntu
  when: ansible_os_family == "Debian"
  block:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install development tools
      apt:
        name:
          - build-essential
          - python3
          - python3-dev
          - python3-pip
          - git
          - wget
          - curl
        state: present

- name: Install Munge (RedHat-based)
  ansible.builtin.yum:
    name:
      - munge
    state: present
  when: ansible_os_family == "RedHat"

- name: Install Munge (Debian-based)
  ansible.builtin.apt:
    name:
      - munge
    state: present
    update_cache: yes
  when: ansible_os_family == "Debian"

- name: Ensure Munge key directory exists
  ansible.builtin.file:
    path: /etc/munge
    state: directory
    owner: munge
    group: munge
    mode: '0700'

- name: Check if Munge key exists
  ansible.builtin.stat:
    path: /etc/munge/munge.key
  register: munge_key

- name: Generate Munge key on controller node
  ansible.builtin.command: /usr/sbin/create-munge-key
  when: inventory_hostname == groups['controller'][0] and not munge_key.stat.exists

- name: Deploy munge key
  ansible.builtin.copy:
    src: "/etc/munge/munge.key"
    dest: "/etc/munge/munge.key"
    owner: munge
    group: munge
    mode: '0400'
  when: inventory_hostname != groups['controller'][0]

- name: Start and enable Munge service
  ansible.builtin.service:
    name: munge
    state: started
    enabled: yes
