---
- name: Remove local file repository
  ansible.builtin.lineinfile:
    path: /etc/apt/sources.list
    regexp: '.*file:///cdrom.*'
    state: absent
    
- name: Add universe repository for Ubuntu
  ansible.builtin.apt_repository:
    repo: 'deb http://archive.ubuntu.com/ubuntu {{ ansible_distribution_release }} universe'
    state: present

- name: Add multiverse repository for Ubuntu
  ansible.builtin.apt_repository:
    repo: 'deb http://archive.ubuntu.com/ubuntu {{ ansible_distribution_release }} multiverse'
    state: present

- name: Add restricted repository for Ubuntu
  ansible.builtin.apt_repository:
    repo: 'deb http://archive.ubuntu.com/ubuntu {{ ansible_distribution_release }} restricted'
    state: present

- name: Add partner repository for Ubuntu
  ansible.builtin.apt_repository:
    repo: 'deb http://archive.canonical.com/ubuntu {{ ansible_distribution_release }} partner'
    state: present

- name: Update apt cache
  ansible.builtin.apt:
    update_cache: yes

