---
- name: Disable SELinux
  ansible.builtin.lineinfile:
    path: /etc/selinux/config
    regexp: '^SELINUX='
    line: 'SELINUX=disabled'
    state: present
  when: ansible_facts['os_family'] == "RedHat"

- name: Disable UFW (Debian)
  ansible.builtin.service:
    name: ufw
    state: stopped
    enabled: no
  when: ansible_facts['os_family'] == "Debian"

- name: Disable Firewalld (RedHat)
  ansible.builtin.service:
    name: firewalld
    state: stopped
    enabled: no
  when: ansible_facts['os_family'] == "RedHat"