---
- name: Check if hwloc is already installed
  stat:
    path: "{{ hwloc_install_dir }}/bin/hwloc-info"
  register: hwloc_installed

- include_tasks: install.yml
  when: not hwloc_installed.stat.exists