---
# tasks file for slurm-repo
- name: Add inventory host mappings to /etc/hosts
  blockinfile:
    path: /etc/hosts
    marker: "# {mark} ANSIBLE INVENTORY HOSTS"
    block: "{{ lookup('template', 'hosts.j2') }}"
    create: yes

- name: Create local nfs repository directory
  file:
    path: "{{ repo_path_root }}"
    state: directory
    mode: '0755'

- name: Copy NFS server packages to nfs-server node
  copy:
    src: "{{ playbook_dir }}/../setup/scripts/offline_repo/{{ item }}"
    dest: "{{ repo_path_root }}/offline_repo/"
  with_items:
    - nfs

- name: Comment out all 'deb' lines in sources.list
  ansible.builtin.replace:
    path: /etc/apt/sources.list
    regexp: '^(?!#)(\s*deb\s+)'
    replace: '# \1'

- name: Add temporary apt repository configuration
  template:
    src: nfs-local.list.j2
    dest: /etc/apt/sources.list.d/nfs-local.list
    mode: '0644'

- name: Verify temporary repository access
  apt:
    update_cache: yes
  register: apt_update_result
  ignore_errors: yes

- name: NFS Server setup
  import_tasks: nfs-server.yml
  when: "'nfs-server' in group_names"

- name: NFS Client setup
  import_tasks: nfs-client.yml
  when: "'compute' in group_names"
