---
# tasks file for slurm-repo

- name: NFS Server setup
  import_tasks: nfs-server.yml
  when: "'nfs-server' in group_names"

- name: NFS Client setup
  import_tasks: nfs-client.yml
  when: "'compute' in group_names"
