---
# tasks file for slurm-repo
- name: Add inventory host mappings to /etc/hosts
  blockinfile:
    path: /etc/hosts
    marker: "# {mark} ANSIBLE INVENTORY HOSTS"
    block: "{{ lookup('template', 'hosts.j2') }}"
    create: yes

- name: Create local nfs repository directory
  file:
    path: "{{ repo_path_root }}"
    state: directory
    mode: '0755'

- name: Copy NFS server packages
  copy:
    src: "{{ playbook_dir }}/../setup/scripts/offline_repo/nfs"
    dest: "{{ repo_path_root }}/offline_repo/nfs"
  when: ansible_facts['os_family'] == "Debian"

- name: Disable default online repositories based on OS version
  import_tasks: pre-setup-deb.yml
  when: ansible_facts['os_family'] == "Debian"

- name: NFS Server setup for Debian
  import_tasks: nfs-server.yml
  when: "'nfs-server' in group_names and ansible_facts['os_family'] == 'Debian'"

- name: NFS Server setup for Rocky
  import_tasks: nfs-server-rocky.yml
  when: "'nfs-server' in group_names and ansible_facts['os_family'] == 'RedHat'"

- name: NFS Client setup for Debian
  import_tasks: nfs-client.yml
  when: "'compute' in group_names and ansible_facts['os_family'] == 'Debian'"

- name: NFS Client setup for Rocky
  import_tasks: nfs-client-rocky.yml
  when: "'compute' in group_names and ansible_facts['os_family'] == 'RedHat'"
