---
- name: Check if NFS server is installed
  command: dpkg -l nfs-kernel-server
  register: nfs_server_check
  ignore_errors: true
  changed_when: false
  run_once: true

- name: Install NFS server packages from temporary repo
  apt:
    name:
      - nfs-kernel-server
    state: present

- name: Create repository directory
  file:
    path: "{{ nfs_repo_path }}"
    state: directory
    mode: '0755'
  run_once: true

- name: Copy offline_repo to NFS repository path
  copy:
    src: "{{ playbook_dir }}/../setup/scripts/offline_repo"
    dest: "{{ nfs_repo_path }}/"
  run_once: true

- name: Configure NFS exports
  lineinfile:
    path: /etc/exports
    line: "{{ nfs_repo_path }} {{ nfs_exports_option }}"
    create: yes
  notify: reload nfs exports
  run_once: true