---
- name: restart munge
  service:
    name: munge
    state: restarted

- name: restart slurmd
  service:
    name: slurmd
    state: restarted
  when: inventory_hostname in groups['compute']

- name: restart slurmdbd
  service:
    name: slurmdbd
    state: restarted
  when: inventory_hostname in groups['controller']

- name: restart slurmctld
  service:
    name: slurmctld
    state: restarted
  when: inventory_hostname in groups['controller']

- name: restart logind
  service:
    name: systemd-logind.service
    state: restarted
    enabled: yes
  when: inventory_hostname in groups['compute']
