---
# handlers file for slurm-repo

- name: update apt cache
  apt:
    update_cache: yes
  when: ansible_os_family == "Debian"

- name: restart nfs server
  service:
    name: nfs-kernel-server
    state: restarted

- name: reload nfs exports
  command: exportfs -ra
