
- name: Install Munge (RedHat-based)
  ansible.builtin.yum:
    name:
      - munge
    state: present
  when: ansible_os_family == "RedHat"

- name: Install Munge (Debian-based)
  ansible.builtin.apt:
    name:
      - munge
    state: present
    update_cache: yes
  when: ansible_os_family == "Debian"

- name: Ensure Munge key directory exists
  ansible.builtin.file:
    path: /etc/munge
    state: directory
    owner: munge
    group: munge
    mode: '0700'

- name: Check if Munge key exists
  ansible.builtin.stat:
    path: /etc/munge/munge.key
  register: munge_key

- name: Generate Munge key on controller node
  ansible.builtin.command: /usr/sbin/create-munge-key
  when: inventory_hostname == groups['controller'][0] and not munge_key.stat.exists

- name: Deploy munge key
  ansible.builtin.copy:
    src: "/etc/munge/munge.key"
    dest: "/etc/munge/munge.key"
    owner: munge
    group: munge
    mode: '0400'
  when: inventory_hostname != groups['controller'][0]

- name: Start and enable Munge service
  ansible.builtin.service:
    name: munge
    state: started
    enabled: yes