---
- name: Include OS-specific tasks
  include_tasks: "{{ ansible_os_family | lower }}.yml"

- name: Create Munge key on the controller node
  command: "/usr/sbin/create-munge-key"
  when: inventory_hostname == groups['controller'][0]

- name: Fetch Munge key from the controller node
  fetch:
    src: /etc/munge/munge.key
    dest: /tmp/munge.key
    flat: yes
  when: inventory_hostname == groups['controller'][0]

- name: Distribute Munge key to compute nodes
  copy:
    src: /tmp/munge.key
    dest: /etc/munge/munge.key
    owner: munge
    group: munge
    mode: '0400'
  delegate_to: "{{ item }}"
  with_items: "{{ groups['compute'] }}"
  when: inventory_hostname != groups['controller'][0]

- name: Ensure Munge service is running
  service:
    name: munge
    state: started
    enabled: yes