---
- name: Run controller-specific Slurm tasks
  include_tasks: controller.yml
  when: inventory_hostname in groups['controller']

- name: Run compute-specific Slurm tasks
  include_tasks: compute.yml
  when: inventory_hostname in groups['compute']
