---
slurm_version: "24.11.0"
slurm_build_dir: "/opt/build/slurm"
slurm_install_dir: "/usr/local"
slurm_config_dir: "/etc/slurm"
slurm_sysconf_dir: "/etc/sysconfig"

# for slurm.conf
slurm_cluster_name: "slurm"
slurm_user: "root"
slurm_user_group: "root"
slurm_partition_name: "gpu"
slurm_account_user: "slurm"

# for slurmdbd.conf
slurmdbd_host_addr: "localhost"
slurmdbd_host: "localhost"
slurm_db_user: "slurm"
slurm_db_pw: "slurmtest"
slurm_db_name: "slurm_acct_db"

# Maximum time to wait for Slurm compute nodes to reboot during playbook setup
slurm_node_reboot_timeout: 600
slurm_autodetect_nvml: true
# Configure pam_slurm_adopt to adopt processes from user SSH into a job cgroup
slurm_enable_pam_slurm_adopt: true
# Restrict user SSH access to only allow users with a running job
slurm_restrict_node_access: true