---
- name: Check local file exists and configure NFS
  hosts: localhost
  tasks:
    - name: Ensure NFS packages exist
      stat:
        path: "{{ playbook_dir }}/../setup/scripts/offline_repo"
      register: local_files

    - name: Fail if .deb files are missing      
      fail:
        msg: "NFS packages not found."
      when: not local_files.stat.exists

- name: Configure NFS
  hosts: all
  roles:
    - slurm-repo
