---
- name: Check local file exists and configure NFS
  hosts: localhost
  tasks:
    - name: Ensure NFS deb packages exist
      stat:
        path: "{{ playbook_dir }}/../setup/scripts/offline_repo"
      register: local_files

    - name: Fail if .deb files are missing      
      fail:
        msg: "NFS .deb packages not found. Please run the download script(./scripts/download-slurm-pkgs-deb.sh) first."
      when: not local_files.stat.exists

- name: Configure NFS
  hosts: all
  roles:
    - slurm-repo
