---
# ansible-galaxy install nvidia.nvidia_driver
- hosts: "{{ hostlist | default('all') }}"
  become: true
  tags:
  - nvidia
  - nvidia_driver
  tasks:
    - name: Check for DGX packages
      stat:
        path: /etc/dgx-release
      register: is_dgx

    - name: install nvidia driver
      include_role:
        name: nvidia.nvidia_driver

    - name: test nvidia-smi
      command: nvidia-smi
      changed_when: false

