---
- name: Prerequisites
  hosts: all
  become: true
  roles:
    - common
    - munge
    - facts

- name: Install components
  hosts: all
  become: true
  roles:
    - hwloc
    - pmix
    - openmpi

- name: Configure Slurm controller
  hosts: controller
  become: true
  tasks:
    - name: Run Slurm controller tasks
      include_role:
        name: slurm
        tasks_from: controller.yml

- name: Configure Slurm compute
  hosts: compute
  become: true
  tasks:
    - name: Run Slurm compute tasks
      include_role:
        name: slurm
        tasks_from: compute.yml

- name: Install enroot
  hosts: compute
  become: true
  roles:
    - nvidia.enroot

- name: Install pyxis
  hosts: compute
  become: true
  roles:
    - pyxis
