---
- name: Prerequisites
  hosts: all
  become: true
  roles:
    - common
    - munge
    - facts

- name: Install components
  hosts: all
  become: true
  roles:
    - hwloc
    - pmix
    - slurm
    - openmpi

- name: Install enroot
  hosts: compute
  become: true
  roles:
    - nvidia.enroot

- name: Install pyxis
  hosts: all
  become: true
  roles:
    - pyxis
