---
- name: Prerequisites
  hosts: all
  become: true
  roles:
    - common
    - munge
    - facts

- name: Install components
  hosts: all
  become: true
  roles:
    - hwloc
    - pmix
    - slurm
    - openmpi
